swagger: "2.0"
info:
  description: "Google Analytics like Service API References"
  version: "0.1"
  title: "Google Analytics like Service API References"
paths:
  /hoge/{name}:
    get:
      summary: "Summary"
      description: "Description"
      parameters:
      - name: "name"
        in: "path"
        description: "hogehoge"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "200Res"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "fuga"